#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp 0/alpha.air.orig 0/alpha.air
cp 0/alpha.water.orig 0/alpha.water

sed 's/inlet/base/g' 0/*

runApplication blockMesh
runApplication topoSet
#runApplication createPatch
#runApplication setFields
#runApplication $(getApplication)

#------------------------------------------------------------------------------
